### ISSUE TITLE
Add missing features

### ISSUE THREAD

**Issue by ingoboerner** [ingoboerner/dracor-ontology#1]
- [ ] : author's wikidata Q-Numbner: There is no designated feature of the author's Wikidata ID. It is so prominent on DraCor, we should add such a feature!
- [ ] Features on authors returned by the former "hidden" author wikidata endpoint, see also below

> For example, the endpoint could be queried to retrieve information about the german author Gotthold Ephraim Lessing using the URL https://dracor.org/api/v1/wikidata/author/Q34628 which returns the following data:

```
{
  "birthDate" : "1729-01-22T00:00:00Z",
  "gender" : "male",
  "birthPlace" : "Kamenz",
  "deathPlace" : "Brunswick",
  "name" : "Gotthold Ephraim Lessing",
  "imageUrl" : "http://commons.wikimedia.org/wiki/Special:FilePath/Gotthold%20Ephraim%20Lessing%20Kunstsammlung%20Uni%20Leipzig.jpg",
  "genderUri" : "http://www.wikidata.org/entity/Q6581097",
  "deathDate" : "1781-02-15T00:00:00Z"
}
```

- [ ]  base: type: string `  "base" : "https://staging.dracor.org/api/v1",` in /info
- [ ] "openapi" : "https://staging.dracor.org/api/v1/openapi.yaml" in /info
- [ ]  commit: type: string in     CorpusInCorpora:
- [ ] uri in PlayInCorpus         uri: type: string format: url
- [ ] digitalSource: nullable: true this is in PlayMetadata: # see dutil:get-corpus-meta-data type: object. does not have a feature in OpenAPI
- [ ] speakers in  Segment data items: type: string

No Ontology references in Object:
```
PlayWithWikidataCharacter:
      # see dutil:get-plays-with-character
      type: object
      properties:
        id:
          type: string
        uri:
          type: string
          format: url
        title:
          type: string
        authors:
          type: array
          items:
            type: string
        characterName:
          type: string
      required:
        - id
        - uri
        - title
        - authors
        - characterName
```
